#Artificial Neural Network 

##Importing the libraries

In [103]:
import numpy as np
import pandas as pd
import tensorflow as tf

##Data Preprocessing

Importing the dataset 

In [104]:
dataset=pd.read_csv('Churn_Modelling.csv')
inputs=dataset.iloc[:,3:-1].values
target=dataset.iloc[:,-1].values
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [105]:
inputs

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [106]:
target

array([1, 0, 1, ..., 1, 1, 0])

Encoding categorical data

Label encoding the "gender" column

In [107]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
inputs[:,2] = le.fit_transform(inputs[:,2])

In [108]:
inputs[:,2]

array([0, 0, 0, ..., 0, 1, 0], dtype=object)

One hot encoding the "Geography" column

In [109]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
inputs = np.array(ct.fit_transform(inputs))

In [110]:
inputs

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

Splitting the dataset into training set and test set

In [111]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size = 0.2, random_state = 1)

Feature scailing

In [112]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)    

##Building the ANN

initializing the ANN

In [113]:
ann=tf.keras.models.Sequential()

adding the input layer and the first hidden layer

In [114]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

adding the second hidden layer

In [115]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

adding the output layer

In [116]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

##Training the ANN

compiling the ANN

In [117]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

training the ANN on the training set

In [118]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.5295 - accuracy: 0.7725
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4630 - accuracy: 0.7986
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4481 - accuracy: 0.8020
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4399 - accuracy: 0.8067
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4346 - accuracy: 0.8085
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4311 - accuracy: 0.8102
Epoch 7/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4288 - accuracy: 0.8117
Epoch 8/100
250/250 [==============================] - 1s 6ms/step - loss: 0.4266 - accuracy: 0.8134
Epoch 9/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4247 - accuracy: 0.8131
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4222 - accura

##Making the predictions and evaluating the model

In [122]:
new_Input=[[1,0,0,600,1,40,3,60000,2,1,1,50000]]
print(ann.predict(sc.transform(new_Input))>0.5)

1/1 [==============================] - 0s 19ms/step
[[False]]


predicting the test results

In [123]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 0]]


Making the confusion matrix

In [124]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1518   67]
 [ 212  203]]


0.8605